namespace ABIStress
{
    internal class Config
    {
        internal const string CallerPrefix = "ABIStress_Caller";
        internal const string CalleePrefix = "ABIStress_Callee";
        // The base seed. This value combined with the index of
        // the caller or callee will uniquely determine how
        // it is generated and which callee is used.
        internal const int Seed = 0xeadbeef;
        // The number of callees to pregenerate.
        // Tailcallers are generated by first selecting a random
        // parameter list. A callee is then selected; to ensure
        // we can actually do a fast tail call, we try to select
        // a callee which requires less incoming arg space. We need
        // to genreate the callees first for this reason.
        internal const int NumCallees = 10000;
        internal static bool Verbose { get; set; }
    }
}
